### PR TITLE
Added comment to default-py-config. (#151)

### PR DESCRIPTION
**Pull request by PhlexPlexico**

### CODE REVIEW

**Comment by PhlexPlexico** [comment]
Make sure you are either an admin OR super admin, it's pointless to be both.

**Comment by MikkelDK** [comment]
> Make sure you are either an admin OR super admin, it's pointless to be both.

It happens, if I'm super_admin! ;) so I can't view.

**Comment by PhlexPlexico** [comment]
Not sure why it isn't working for you, as it was confirmed by the issue that it was resolved by the other person. Are you inputting the correct Steam ID for super admins?

**Comment by MikkelDK** [comment]
> Not sure why it isn't working for you, as it was confirmed by the issue that it was resolved by the other person. Are you inputting the correct Steam ID for super admins?

Yep. my steamID.
I did used steamID64: > "76561198383180718"

@PhlexPlexico 
I can try with steamID normal example: "STEAM_0:0:211457495"

**Comment by PhlexPlexico** [comment]
@MikkelDK now this should be resolved. Moving this into master. If there continues to be an error, please create an issue. Thanks!

**Pull request merged**
